# Dataset configuration for YOLO detection and segmentation
path: C:\Users\rares\OneDrive\Desktop\data\dataset

train: images/train
val: images/val

labels:
  train: labels/train
  val: labels/val

masks:
  train: masks/train
  val: masks/val

nc: 1  # Number of classes
names: ["seat_pice"]

task: segment  # Supports both detection and segmentation
